# Generated by Django 5.2.8 on 2025-12-01 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GlucoseReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                (
                    "glucose_level",
                    models.IntegerField(verbose_name="Glucose Level (mg/dL)"),
                ),
                (
                    "measurement_type",
                    models.CharField(
                        choices=[
                            ("fasting", "Fasting"),
                            ("pre_breakfast", "Pre Breakfast"),
                            ("post_breakfast", "Post Breakfast"),
                            ("pre_lunch", "Pre Lunch"),
                            ("post_lunch", "Post Lunch"),
                            ("pre_dinner", "Pre Dinner"),
                            ("post_dinner", "Post Dinner"),
                            ("bedtime", "Bedtime"),
                            ("night", "Night"),
                        ],
                        max_length=20,
                        verbose_name="Measurement Type",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glucose_readings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Glucose Reading",
                "verbose_name_plural": "Glucose Readings",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("breakfast", "Breakfast"),
                            ("lunch", "Lunch"),
                            ("dinner", "Dinner"),
                            ("snack", "Snack"),
                        ],
                        max_length=20,
                        verbose_name="Meal Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="AI generated description",
                        verbose_name="Description",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="meals/%Y/%m/%d/", verbose_name="Photo"
                    ),
                ),
                (
                    "estimated_calories",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Estimated Calories"
                    ),
                ),
                (
                    "carbs_estimate",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Carbs Estimate (g)"
                    ),
                ),
                (
                    "manual_notes",
                    models.TextField(blank=True, verbose_name="Manual Notes"),
                ),
                (
                    "ai_response_raw",
                    models.JSONField(
                        blank=True, null=True, verbose_name="AI Response Raw"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Meal",
                "verbose_name_plural": "Meals",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "diagnosis_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Diagnosis Date"
                    ),
                ),
                (
                    "target_glucose_min",
                    models.IntegerField(
                        default=70, verbose_name="Target Glucose Min (mg/dL)"
                    ),
                ),
                (
                    "target_glucose_max",
                    models.IntegerField(
                        default=180, verbose_name="Target Glucose Max (mg/dL)"
                    ),
                ),
                (
                    "language_preference",
                    models.CharField(
                        choices=[("it", "Italian"), ("en", "English")],
                        default="it",
                        max_length=2,
                        verbose_name="Language Preference",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
