# Generated by Django 5.2.8 on 2025-12-01 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glucose_tracker", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasurementSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mon_pre_breakfast",
                    models.BooleanField(
                        default=False, verbose_name="Monday - Pre Breakfast"
                    ),
                ),
                (
                    "mon_post_breakfast",
                    models.BooleanField(
                        default=False, verbose_name="Monday - Post Breakfast"
                    ),
                ),
                (
                    "mon_pre_lunch",
                    models.BooleanField(
                        default=False, verbose_name="Monday - Pre Lunch"
                    ),
                ),
                (
                    "mon_post_lunch",
                    models.BooleanField(
                        default=False, verbose_name="Monday - Post Lunch"
                    ),
                ),
                (
                    "mon_pre_dinner",
                    models.BooleanField(
                        default=False, verbose_name="Monday - Pre Dinner"
                    ),
                ),
                (
                    "mon_post_dinner",
                    models.BooleanField(
                        default=False, verbose_name="Monday - Post Dinner"
                    ),
                ),
                (
                    "mon_bedtime",
                    models.BooleanField(default=False, verbose_name="Monday - Bedtime"),
                ),
                (
                    "tue_pre_breakfast",
                    models.BooleanField(
                        default=False, verbose_name="Tuesday - Pre Breakfast"
                    ),
                ),
                (
                    "tue_post_breakfast",
                    models.BooleanField(
                        default=False, verbose_name="Tuesday - Post Breakfast"
                    ),
                ),
                (
                    "tue_pre_lunch",
                    models.BooleanField(
                        default=False, verbose_name="Tuesday - Pre Lunch"
                    ),
                ),
                (
                    "tue_post_lunch",
                    models.BooleanField(
                        default=False, verbose_name="Tuesday - Post Lunch"
                    ),
                ),
                (
                    "tue_pre_dinner",
                    models.BooleanField(
                        default=False, verbose_name="Tuesday - Pre Dinner"
                    ),
                ),
                (
                    "tue_post_dinner",
                    models.BooleanField(
                        default=False, verbose_name="Tuesday - Post Dinner"
                    ),
                ),
                (
                    "tue_bedtime",
                    models.BooleanField(
                        default=False, verbose_name="Tuesday - Bedtime"
                    ),
                ),
                (
                    "wed_pre_breakfast",
                    models.BooleanField(
                        default=False, verbose_name="Wednesday - Pre Breakfast"
                    ),
                ),
                (
                    "wed_post_breakfast",
                    models.BooleanField(
                        default=False, verbose_name="Wednesday - Post Breakfast"
                    ),
                ),
                (
                    "wed_pre_lunch",
                    models.BooleanField(
                        default=False, verbose_name="Wednesday - Pre Lunch"
                    ),
                ),
                (
                    "wed_post_lunch",
                    models.BooleanField(
                        default=False, verbose_name="Wednesday - Post Lunch"
                    ),
                ),
                (
                    "wed_pre_dinner",
                    models.BooleanField(
                        default=False, verbose_name="Wednesday - Pre Dinner"
                    ),
                ),
                (
                    "wed_post_dinner",
                    models.BooleanField(
                        default=False, verbose_name="Wednesday - Post Dinner"
                    ),
                ),
                (
                    "wed_bedtime",
                    models.BooleanField(
                        default=False, verbose_name="Wednesday - Bedtime"
                    ),
                ),
                (
                    "thu_pre_breakfast",
                    models.BooleanField(
                        default=False, verbose_name="Thursday - Pre Breakfast"
                    ),
                ),
                (
                    "thu_post_breakfast",
                    models.BooleanField(
                        default=False, verbose_name="Thursday - Post Breakfast"
                    ),
                ),
                (
                    "thu_pre_lunch",
                    models.BooleanField(
                        default=False, verbose_name="Thursday - Pre Lunch"
                    ),
                ),
                (
                    "thu_post_lunch",
                    models.BooleanField(
                        default=False, verbose_name="Thursday - Post Lunch"
                    ),
                ),
                (
                    "thu_pre_dinner",
                    models.BooleanField(
                        default=False, verbose_name="Thursday - Pre Dinner"
                    ),
                ),
                (
                    "thu_post_dinner",
                    models.BooleanField(
                        default=False, verbose_name="Thursday - Post Dinner"
                    ),
                ),
                (
                    "thu_bedtime",
                    models.BooleanField(
                        default=False, verbose_name="Thursday - Bedtime"
                    ),
                ),
                (
                    "fri_pre_breakfast",
                    models.BooleanField(
                        default=False, verbose_name="Friday - Pre Breakfast"
                    ),
                ),
                (
                    "fri_post_breakfast",
                    models.BooleanField(
                        default=False, verbose_name="Friday - Post Breakfast"
                    ),
                ),
                (
                    "fri_pre_lunch",
                    models.BooleanField(
                        default=False, verbose_name="Friday - Pre Lunch"
                    ),
                ),
                (
                    "fri_post_lunch",
                    models.BooleanField(
                        default=False, verbose_name="Friday - Post Lunch"
                    ),
                ),
                (
                    "fri_pre_dinner",
                    models.BooleanField(
                        default=False, verbose_name="Friday - Pre Dinner"
                    ),
                ),
                (
                    "fri_post_dinner",
                    models.BooleanField(
                        default=False, verbose_name="Friday - Post Dinner"
                    ),
                ),
                (
                    "fri_bedtime",
                    models.BooleanField(default=False, verbose_name="Friday - Bedtime"),
                ),
                (
                    "sat_pre_breakfast",
                    models.BooleanField(
                        default=False, verbose_name="Saturday - Pre Breakfast"
                    ),
                ),
                (
                    "sat_post_breakfast",
                    models.BooleanField(
                        default=False, verbose_name="Saturday - Post Breakfast"
                    ),
                ),
                (
                    "sat_pre_lunch",
                    models.BooleanField(
                        default=False, verbose_name="Saturday - Pre Lunch"
                    ),
                ),
                (
                    "sat_post_lunch",
                    models.BooleanField(
                        default=False, verbose_name="Saturday - Post Lunch"
                    ),
                ),
                (
                    "sat_pre_dinner",
                    models.BooleanField(
                        default=False, verbose_name="Saturday - Pre Dinner"
                    ),
                ),
                (
                    "sat_post_dinner",
                    models.BooleanField(
                        default=False, verbose_name="Saturday - Post Dinner"
                    ),
                ),
                (
                    "sat_bedtime",
                    models.BooleanField(
                        default=False, verbose_name="Saturday - Bedtime"
                    ),
                ),
                (
                    "sun_pre_breakfast",
                    models.BooleanField(
                        default=False, verbose_name="Sunday - Pre Breakfast"
                    ),
                ),
                (
                    "sun_post_breakfast",
                    models.BooleanField(
                        default=False, verbose_name="Sunday - Post Breakfast"
                    ),
                ),
                (
                    "sun_pre_lunch",
                    models.BooleanField(
                        default=False, verbose_name="Sunday - Pre Lunch"
                    ),
                ),
                (
                    "sun_post_lunch",
                    models.BooleanField(
                        default=False, verbose_name="Sunday - Post Lunch"
                    ),
                ),
                (
                    "sun_pre_dinner",
                    models.BooleanField(
                        default=False, verbose_name="Sunday - Pre Dinner"
                    ),
                ),
                (
                    "sun_post_dinner",
                    models.BooleanField(
                        default=False, verbose_name="Sunday - Post Dinner"
                    ),
                ),
                (
                    "sun_bedtime",
                    models.BooleanField(default=False, verbose_name="Sunday - Bedtime"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measurement_schedule",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
